### ISSUE TITLE
Zenodo integration and DOI assignment

### ISSUE THREAD

**Issue by drsteve** [jhaiduce/advect1d#4]
AGU's open data policy (which includes software) needs software that folks are using to be citable. For open-source software, the github repository is not sufficent (well, some editors will let it slide still).

So can I ask @jhaiduce to:
1. Enable Zenodo integration for this repo
2. Make a release from the last commit
3. Make sure the metadata over at Zenodo is intelligible (real names instead of github usernames, date that corresponds to commit not sync, etc.)

And then I'll be in touch separately about whether or not you think co-authorship is warranted...

**Comment by jhaiduce** [comment]
I'm most of the way there, but before I publish the Zenodo DOI's, does Amanda Stricklan have an ORCID ID?

**Comment by drsteve** [comment]
She should, but I can't actually find my record of it. I'll check in with her, but you can edit the metadata of a Zenodo record after the fact so adding her ORCID after the DOI is minted should work too...

**Comment by jhaiduce** [comment]
> you can edit the metadata of a Zenodo record after the fact

Didn't know that. I'll go ahead and publish then. By the way, you'll see the most recent version is dated today, but the only change from the version you used is that I added a license file.

**Comment by jhaiduce** [comment]
Ok, here it is: 

- https://doi.org/10.5281/zenodo.7036066 is the latest version
- https://doi.org/10.5281/zenodo.7035924 is the older version (same as latest but missing a license file)
- https://doi.org/10.5281/zenodo.7035923 points to all versions

**Comment by drsteve** [comment]
Just got around to actually copying the Zenodo citation data into a bibtex file and I noticed that the citation data has an unexpected author ordering:
```
Steve Morley, John Haiducek, & Amanda Stricklan. (2022). jhaiduce/advect1d: 1.0.1 (1.0.1). Zenodo. https://doi.org/10.5281/zenodo.7036066
```
Surely that should be Haiducek et al., not Morley et al.?

**Comment by jhaiduce** [comment]
> Surely that should be Haiducek et al., not Morley et al.?

Good catch. I've updated the author ordering in the Zenodo records.

Incidentally, it looks like it was ordering names according to commit counts. Github reports you having more commits than me because a bunch of my older commits used a different e-mail address that doesn't correspond with my github account.
